### PR TITLE
Deprecate rtm.start

### PR DESCRIPTION
**Pull request by Luke9389**
Issue: https://github.com/Expensify/Expensify/issues/186859

As you can see in the linked issue, Slack is deprecating the `rtm.start` endpoint, which was returning a very large glob of data. Now that Slack is servicing thousands of users per workspace, they've elected to clean this up by introducing a more refined connection endpoint `rtm.connect`, which returns only the essentials. 

The changes made in this PR adjust the way we source data upon connection. Rather than taking it from the `rtm.start` endpoint, we're hitting individual endpoints as needed for each type of data.

Stylistically speaking, I've elected to keep the format that was here previously. For example (no return type): 
```php
public function fetchUsers()
{
    $this->apiCall('users.list', [
        'presence' => 1,
    ])->then(function (Payload $response) {
        foreach ($response['members'] as $user) {
            $this->users[$user['id']] = new User($this, $user);
        }
    });
}
```

While `$this->getGroups` does return a list of Group objects, we were previously storing them in an associative array with their `id`s as keys. Hence the following foreach block: 

```php
  ->then(function () {
      // populate list of groups
      $groups = $this->getGroups();
      foreach ($groups as $group) {
          $this->groups[$group['id']] = $group;
      }
  })
```

### CODE REVIEW

**Comment by Luke9389** [comment]
@tgolen, I've put forward a draft of changes, but I'm unsure about two things
1) Is the code style OK? I decided to go for a promise chain rather than using promise all. 
2) How should I test this? My thought is that I should be able to use composer to install this branch of `slack-client` in my Chronos repo. I haven't really looked into it though-I figured you'd have the answer on hand. Let me know if that wasn't a safe assumption.

**Comment by tgolen** [comment]
Hey, Luke. The code style is fine. I think keeping it consistent with the existing codebase is the best path.

As for testing it, you could just run chronos locally, and copy these changes to the `vendor` directory. Once you've verified the changes, then we will need to merge this PR. Once it's merged, we need to create a release tag in this repo and it should get updated in the repos that use it. Actually, I'm a little fuzzy about how it gets updated in the other repos, but @deetergp knows for sure if it's not written in this readme already.

**Comment by deetergp** [comment]
It has been a hot minute since the last time I've changed anything in this repo (~3 years) but looking at `composer.json` the Chronos repo, we're checked out to `master`. In order to test your branch locally, inside your local copy of the Chronos repo's `composer.json`, change `"coderstephen/slack-client": "master"` to `"coderstephen/slack-client": "dev-luke-deprecate-rtm.start"`, then run `composer update coderstephen/slack-client`. You can double-check `vendor/coderstephen/slack-client/ApiClient.php` to see if your new `getBots` method is there.

**Comment by Luke9389** [comment]
Didn't get the opportunity to test this today, but I'll be circling back to this tomorrow

**Comment by Luke9389** [comment]
I realized that my first attempt here was off because `RealTimeClient` extends `ApiClient` and was overwriting the `getSomething` methods because it's `.connect` method was already setting all the data (i.e. `RealTimeClient` didn't have a use for the get methods that it was inheriting so they just returned the stored data). 

So now I've given `RealTimeClient` some `fetchSomething` metods that will make API calls to fetch data. This way we can call those fetch methods during the `connect` method, while keeping the current overwritten `get` methods and their references in tact. 

Currently I'm fighting off this error, which is indicating to me that the users data is not being set properly. More on that tomorrow. 
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Plugin_PresenceManager::updateUsersPresence() must be of the type array, null given, called in /Users/lukedonahue/Expensidev/Chronos/lib/Plugin/PresenceManager.php on line 29 and defined in /Users/lukedonahue/Expensidev/Chronos/lib/Plugin/PresenceManager.php:44
Stack trace:
#0 /Users/lukedonahue/Expensidev/Chronos/lib/Plugin/PresenceManager.php(29): Plugin_PresenceManager->updateUsersPresence(NULL, 'active')
#1 [internal function]: Plugin_PresenceManager->{closure}(Object(Slack\Payload))
#2 /Users/lukedonahue/Expensidev/Chronos/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#3 /Users/lukedonahue/Expensidev/Chronos/vendor/coderstephen/slack-client/src/RealTimeClient.php(532): Slack\RealTimeClient->emit('presence_change', Array)
#4 /Users/lukedonahue/Expensidev/Chronos/vendor/coderstephen/slack-client/src/RealTimeClient.php(123): Slack\RealTimeClient->onMessage(Object(Devristo\Phpws\Messaging\WebSocketMess in /Users/lukedonahue/Expensidev/Chronos/lib/Plugin/PresenceManager.php on line 44
```

**Comment by Luke9389** [comment]
So I'm thinking I'm not properly chaining these async functions together.
Gonna try a few more formulations, perhaps a promise.all will do the trick.

**Comment by Luke9389** [comment]
OK, I got this working, but admittedly in a bit of a strange way. 
The above error was being thrown from PresenceManager.php in Chronos [here](https://github.com/Expensify/Chronos/blob/173367f77633d4ab4fa9ef031e4b86b3c7186d58/lib/Plugin/PresenceManager.php#L29).

https://github.com/Expensify/Chronos/blob/173367f77633d4ab4fa9ef031e4b86b3c7186d58/lib/Plugin/PresenceManager.php#L27-L30

I tried `var_dump`ing the `$data` variable right before it, and got this: 
```php
object(Slack\Payload)#200 (1) {
  ["data":protected]=>
  array(3) {
    ["type"]=>
    string(15) "presence_change"
    ["presence"]=>
    string(4) "away"
    ["user"]=>
    string(9) "U6Y1LDSD6"
  }
}
```
Initially, we were expecting to see a `"users"` key here, not just a single `"user"`. When I dump this, one of these logs comes in for each user.
I'm not sure why this change has happened. It must be due to the way I'm setting users. However, by making the following change in PresenceManager, we end up fixing the error. It's a _tad_ hacky, but I'm thinking it might be best to leave it because it doesn't mess with the case when the `"users"` key exists. 

```diff
-   $this->updateUsersPresence($data['users'], $data['presence']);
+   $this->updateUsersPresence($data['users'] ?? [$data['user']], $data['presence']);
```

I've made the change, so I'll just commit it to a draft PR and we can discuss further if need be.

**Comment by Luke9389** [comment]
I somehow missed that this didn't have reviewers. It is ready to go though.

**Comment by Luke9389** [comment]
@tgolen I need your input on whether this solution is acceptable. https://github.com/Expensify/slack-client/pull/4#issuecomment-1011516691

The TL;DR is that this _slightly_ changed the data structure that the slack client returns. Everything still works if we make the change in the Chronos repo that I mentioned above.

**Comment by tgolen** [comment]
> @tgolen I need your input on whether this solution is acceptable. #4 (comment)

I think your change is fine. We're going to be throwing away this code in the future when Chronos is fully moved to App, so I'm not too concerned over what state it's in.

**Review by tgolen — APPROVED** [review]

**Comment by tgolen** [comment]
I haven't tested this at all, and the PR description doesn't really mention any tests. Are there any tests you can come up with so that when it's deployed, we can do some quick testing to verify it's all working? I think you'll need to keep a pretty close watch on this for a day or two once it's deployed. There is a chance that something is breaking and it will be difficult to track down exactly what the cause is.

**Comment by Luke9389** [comment]
Yep, I'll add some detailed tests in the testing section. I agree, this one will be a bit spicy to deploy, so I'll be vigilant about buggy chronos behavior.

**Comment by tgolen** [comment]
OK, it's merged. I'll let you decide when you want to deploy it!

**Comment by Luke9389** [comment]
Ok perfect! Thanks. I've got a few irons in the fire today :)

**Pull request merged**
